name: Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: yarn install --dev
      
    - name: Run tests
      run: yarn test # -- --max-warnings 0

    - name: Run ESLint
      run: yarn lint # -- --max-warnings 0

    - name: Build
      run: yarn build

    - name: Check dist files are up to date
      run: |
        if [ -n "$(git status --porcelain dist)" ]; then
            echo "error: dist files are not up to date"
            exit 1
        fi
